apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-11-23T07:03:42Z"
  generation: 2
  labels:
    app: feedbackapi-dp
  name: feedbackapi-dp
  namespace: default
  resourceVersion: "12790"
  uid: 9b8c9a94-9300-4873-baa9-2cb2c5817225
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: feedbackapi-dp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: feedbackapi-dp
    spec:
      containers:
      - image: labdev11/feedbackapi:v1
        imagePullPolicy: IfNotPresent
        name: feedbackapi
        livenessProbe:
          httpGet:
            path: /feedback
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  conditions:
  - lastTransitionTime: "2022-11-23T07:03:42Z"
    lastUpdateTime: "2022-11-23T07:03:53Z"
    message: ReplicaSet "feedbackapi-dp-77df5597b9" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-11-23T07:25:05Z"
    lastUpdateTime: "2022-11-23T07:25:05Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  observedGeneration: 2
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 2
  