apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2022-11-23T07:03:23Z"
  generation: 2
  labels:
    app: logicapi-dp
  name: logicapi-dp
  namespace: default
  resourceVersion: "12138"
  uid: 1cd94ec1-af46-42cf-8015-9a04b8689a44
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: logicapi-dp
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: logicapi-dp
    spec:
      containers:
      - image: labdev11/logicapi:v1
        imagePullPolicy: IfNotPresent
        name: logicapi
        livenessProbe:
          httpGet:
            path: /polarity
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 30
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2022-11-23T07:03:23Z"
    lastUpdateTime: "2022-11-23T07:03:38Z"
    message: ReplicaSet "logicapi-dp-58c969d54d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2022-11-23T07:33:55Z"
    lastUpdateTime: "2022-11-23T07:33:55Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
  